### ISSUE TITLE
Failure to load project with layers coming from S3 bucket

### ISSUE THREAD

**Issue by NyakudyaA** [g3w-suite/g3w-admin#174]
I am running the latest dev version from https://github.com/g3w-suite/g3w-suite-docker

I have added a couple of env variables to my compose file like

```yml
g3w-suite:

  image: g3wsuite/g3w-suite:dev
  environment:
    - G3WSUITE_TILECACHE_PATH
    - G3WSUITE_QDJANGO_SERVER_URL
    - G3WSUITE_POSTGRES_DBNAME
    - G3WSUITE_POSTGRES_USER
    - G3WSUITE_POSTGRES_USER_LOCAL
    - G3WSUITE_POSTGRES_PASS
    - G3WSUITE_POSTGRES_HOST
    - G3WSUITE_POSTGRES_PORT
    - TILESTACHE_CACHE_BUFFER_SIZE
    - TILESTACHE_CACHE_TOKEN
    - PGSERVICEFILE
    - AWS_ACCESS_KEY_ID
    - AWS_S3_ENDPOINT
    - AWS_SECRET_ACCESS_KEY
    - AWS_VIRTUAL_HOSTING
```
When I log in to the container I can execute
```
gdalinfo /vsis3/foo/foobar.tif
```
And I can see the results of gdal. However, when I try to upload the QGIS file with this remote source I get the error

![remote](https://user-images.githubusercontent.com/2510900/102237831-bc326780-3efd-11eb-93df-ebc64aabc3dd.png)

It seems that when the project properties are being extracted something is failing.

I tried to run the same setting with the native QGIS server and it works seamlessly
