### ISSUE TITLE
Automatically delete pull request branches after they have been merged

### ISSUE THREAD

**Issue by Raruto** [g3w-suite/g3w-admin#441]
> Related to: https://github.com/g3w-suite/g3w-client/issues/122, https://github.com/g3w-suite/g3w-client/pull/120, repositories can also be set to delete the head branch of a pull request once it has merged into the base branch:
>
> - [Managing the automatic deletion of branches](https://help.github.com/en/articles/managing-the-automatic-deletion-of-branches)

Ref: https://github.com/g3w-suite/g3w-client/issues/123

**Comment by wlorenzetti** [comment]
@Raruto it could be right, but some times is necessary to do a back port of a fix for example, so I think is better delete the branch by hand.

**Comment by Raruto** [comment]
> some times is necessary to do a back port of a fix for example, so I think is better delete the branch by hand.

Ok, but since I know it can be quite easy to forget some along the way..

For this specific use case we could also evaluate the use of a dedicated "backporting" action (at least for the most trivial cases):

---

### • [tibdex/backport](https://github.com/tibdex/backport)

> Backport is a [JavaScript GitHub Action](https://help.github.com/en/articles/about-actions#javascript-actions) to backport a pull request by simply adding a label to it.
>
> It can backport [rebased and merged](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-request-merges#rebase-and-merge-your-pull-request-commits) pull requests with a single commit and [squashed and merged](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-request-merges#squash-and-merge-your-pull-request-commits) pull requests.
It thus integrates well with [Autosquash](https://github.com/marketplace/actions/autosquash).
> 
> ## Usage
>
> 1.  :electric_plug: Add this [.github/workflows/backport.yml](https://github.com/tibdex/backport/blob/main/.github/workflows/backport.yml) to your repository.
>
> 2.  :speech_balloon: Let's say you want to backport a pull request on a branch named `production`.
>
>    Then label it with `backport production`. (See [how to create labels](https://help.github.com/articles/creating-a-label/).)
>
> 3.  :sparkles: That's it! When the pull request gets merged, it will be backported to the `production` branch.
    If the pull request cannot be backported, a comment explaining why will automatically be posted.
>
> _Note:_ multiple backport labels can be added.
> For example, if a pull request has the labels `backport staging` and `backport production` it will be backported to both branches: `staging` and `production`.

---

### • [geonode/.github/workflows/backport.yml](https://github.com/GeoNode/geonode/blob/49c435bcf3dce16f429be5062d64116e3d31a387/.github/workflows/backport.yml)

```yml
name: Backport
on:
  pull_request_target:
    types:
      - closed
      - labeled

jobs:
  backport:
    name: Backport
    runs-on: ubuntu-latest
    # Only react to merged PRs for security reasons.
    # See https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target.
    if: >
      github.event.pull_request.merged
      && (
        github.event.action == 'closed'
        || (
          github.event.action == 'labeled'
          && contains(github.event.label.name, 'backport')
        )
      )
    steps:
      - name: Backporting
        uses: tibdex/backport@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
```

Sample integration: https://github.com/GeoNode/geonode/pulls
